networks:
  internal:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      internal:

  migration:
    build: .
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_CONTAINER_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_KEY=${DJANGO_KEY}
      - PYTHONPATH=${PYTHONPATH}
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate
    networks:
      internal:

  django:
    build: .
    container_name: django
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_CONTAINER_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_KEY=${DJANGO_KEY}
      - DJANGO_CONTAINER_HOST=${DJANGO_CONTAINER_HOST}
      - PYTHONPATH=${PYTHONPATH}
    depends_on:
      migration:
        condition: service_completed_successfully
    command: python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      internal:

  tests:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_CONTAINER_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_KEY=${DJANGO_KEY}
      - PYTHONPATH=${PYTHONPATH}
    command: >
      dockerize -wait tcp://django:8000 -timeout 10s
      python manage.py test tests.test_integration.test_setup
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      internal:
